### PR TITLE
Use `SwiftInfo` `compilation_context`

### PR DESCRIPTION
**Pull request by brentleyjones**
Related to #94.

This adds support for `private_deps`.

| Before | After |
| - | - |
| CleanShot 2022-04-24 at 20 57 45@2x | CleanShot 2022-04-24 at 20 58 39@2x |

### CODE REVIEW

**Comment by cgrindel** [comment]
@brentleyjones So that we are on the same page, I believe that this PR will obsolete #338. The only item that is not covered is the change to the `is_swift` logic. However, that may not be relevant as you are not applying the `swift_clang_module_aspect` now that `rules_swift` passes along the compilation context. Does this sound right to you?

**Comment by brentleyjones** [comment]
Yeah, I think this fully obsoletes #338. We can leave the `is_swift` logic alone for now.

**Comment by cgrindel** [comment]
Are you still working this PR? It is marked as WIP.

**Review by cgrindel — APPROVED** [review]

**Comment by cgrindel** [comment]
FYI. I tested your changes against a real-world example using the SwiftSyntax stuff. It compiles.

**Pull request merged**
