### PR TITLE
Set `target.swift-*` lldb settings

### PR DESCRIPTION
**Pull request by brentleyjones**
Part of #617.

This allows lldb to work correctly if using the `-noserialize-debugging-options` `swiftc` flag.

### CODE REVIEW

**Comment by brentleyjones** [comment]
I need to fix the lldb module name matching, as these two are not equal:
```
/Users/brentley/Library/Developer/CoreSimulator/Devices/7022ED79-E71C-425C-BA0E-634AD3375CD2/data/Containers/Bundle/Application/C23EF714-036C-4EE5-BB91-EF2F66E0AE33/Example.app/Example_ExecutableName
/Users/brentley/Library/Developer/Xcode/DerivedData/bwb-ezjualidhmoodmfdrsrwmwoehsyl/Build/Products/bazel-out/ios-x86_64-min15.0-applebin_ios-ios_x86_64-dbg-ST-a0d0e3b8f217/bin/Example/Example.app/Example_ExecutableName
```

**Comment by brentleyjones** [comment]
Almost there. These two keys don't match. Trying to figure out when we need to add the minimum os to the triple:
```
"arm64-apple-macosx11.0.0 tests.xctest/Contents/MacOS/tests"
"arm64-apple-macosx tests.xctest/Contents/MacOS/tests"
```

**Comment by brentleyjones** [comment]
I swear I was seeing the triples without the os version before. Now I only see the one with os version. Maybe I can add a fallback key lookup just in case...

**Comment by brentleyjones** [comment]
Regardless, latest issue is that these two don't match:
```
lldb: "arm64-apple-macosx11.0.0 tests.xctest/Contents/MacOS/tests"
generated: "arm64-apple-macosx12.0.0 tests.xctest/Contents/MacOS/tests"
```

I have `--macos_minimum_os=12.0` set, so I'm not sure what's up with that yet.

**Comment by brentleyjones** [comment]
And now it works. Hmmmmm 🤔. I'm thinking it was some sort of caching issue, so we just need the one backup now, though maybe I can convert the lldb one to the generic one when doing that. The downside is the small chance of collisions if there are multiple versions of executable paths that only differ on os version, but the backup is better than nothing.

**Comment by brentleyjones** [comment]
Fallback added, I think this is good to go.

@jpsim It would be nice to make sure that this doesn't regress debugging for EM. It doesn't set the flag that removes debug information (`--features=swift.cacheable_swiftmodules`) but EM already sets that, so this should only improve debugging of Swift code for you.

@cgrindel can you test this on your internal project as well?

**Comment by brentleyjones** [comment]
(And I found the 11.0 vs 12.0, and it's related to generator's tests. Digging in.)

**Comment by brentleyjones** [comment]
And now that is fixed! Was looking at yet another wrong place for the triple. So many places to get it in lldb...

**Comment by jpsim** [comment]
Lightweight debugging testing with EM seems to still work. I didn't review the changes here in depth though, there's a lot that was touched.

**Comment by brentleyjones** [comment]
I got a couple offline reports of this working, so merging.

**Pull request merged**
