### PR TITLE
Upgrade rules_swift to 1.4.0

### PR DESCRIPTION
**Pull request by brentleyjones**

### CODE REVIEW

**Comment by brentleyjones** [comment]
https://github.com/bazelbuild/rules_swift/pull/940

**Comment by brentleyjones** [comment]
https://github.com/bazelbuild/rules_swift/pull/945

**Comment by maxwellE** [comment]
Top hatting this now in our build

**Comment by maxwellE** [comment]
Works for us in our build

**Comment by brentleyjones** [comment]
:+1: I need to change this to 1.4.0 now, then I'll merge.

**Pull request merged**
