### PR TITLE
Create symlinks during project generation

### LINKED ISSUE #848: Bug: Files and folders don't resolve in Xcode until build or next open
## Describe the bug

When first generating an Xcode project, some files and folders don't resolve in Xcode. They're red in the project navigator, files aren't available to quick-open, search results from those files don't show up etc.

If I then build a target, the _folders_ resolve and are no longer red, but the files are still red and not resolved.

If I then close and re-open the Xcode project, the files now resolve.

|First Open|After Build 1| After Build 2|After Re-Open|
|-|-|-|-|
|image|image|image|image|

## Reproduction steps

1. Clone https://github.com/jpsim/swiftlint-bazel-example
2. Generate the Xcode project: `bazel run :swiftlint_xcodeproj`
3. Open the Xcode project: `xed .`
4. Notice the unresolved folders and files in the project navigator
5. Build the `swiftlint` scheme
6. Notice the folders are now resolved
7. Close & re-open the Xcode project
8. Notice the files are now resolved

## Expected behavior

Files and folders should resolve correctly when first opening a generated Xcode project.

## Versions
- Bazel: 5.2.0
- rules_xcodeproj: 1cc0245336bf17d0a8483da21048faeb14ac53a9
- rules_apple: 1.0.1
- rules_swift: 1.0.0

### PR DESCRIPTION
**Pull request by brentleyjones**
Fixes #848.

### CODE REVIEW

**Comment by jpsim** [comment]
🤔  I'm not seeing any change over https://github.com/buildbuddy-io/rules_xcodeproj/commit/1cc0245336bf17d0a8483da21048faeb14ac53a9 when following the repro steps in #848.

I'm also running `git clean -xdf && bazel clean --expunge` between rounds of testing, if that helps.

**Comment by brentleyjones** [comment]
When do you call those commands? If it's after project gen you'll run into issues. If it's before project gen it should work. I'll double check though.

**Comment by brentleyjones** [comment]
Ahh, so this fixes the generated files, but not the external files, when cleaning like you do. Looking into it.

**Comment by jpsim** [comment]
I'm cleaning before project gen. `git clean -xdf && bazel clean --expunge && bazel run :swiftlint_xcodeproj && xed .`

**Comment by brentleyjones** [comment]
I had a typo when I refactored some stuff, fixed now.

**Review by jpsim — APPROVED** [review]
Confirmed #848 is fixed. Thanks!

**Pull request merged**
