### PR TITLE
Support `includes` in cc_library

### PR DESCRIPTION
**Pull request by jpsim**
By specifying `SYSTEM_HEADER_SEARCH_PATHS` in Xcode build settings.

Partially addresses https://github.com/buildbuddy-io/rules_xcodeproj/issues/82.

Allows [Yams](https://github.com/jpsim/Yams) to compile.

### CODE REVIEW

**Comment by brentleyjones** [comment]
This _should_ be handled by the other mechanisms that collect header include paths. Ideally we don't look at `ctx.attr` if possible, to allow custom rules to "just work".

Can you debug a bit to see where the disconnect is? We look at `CcInfo.compilation_context`, which should have these.

**Comment by brentleyjones** [comment]
Looks like `cc_library` sets these in [`CcInfo.compilation_context.system_includes`](https://docs.bazel.build/versions/main/skylark/lib/CompilationContext.html#system_includes). I thought that was going to be for SDK paths, but thankfully it's not.

So, the more complete fix is to parse that in `_process_search_paths()` and set it to `SYSTEM_HEADER_SEARCH_PATHS` in`generator`. Also, we should parse `-isystem` in `opts.bzl` similar to `-iquote` and have `opts_search_paths` have a `system_includes`.

**Comment by jpsim** [comment]
Thanks for the guidance (again!). I applied what I think you asked for, and confirmed that Yams is still compiling in Xcode with the changes. Let me know if I misinterpreted something.

**Review by brentleyjones — APPROVED** [review]
Perfect! Thanks!

**Pull request merged**
