### PR TITLE
Fix duplicate `LinkerInputs.staticLibraries` error

### LINKED ISSUE #764: "Decoded elements aren't unique" error
As of c538247afae41ffef463b6d1d1856453b0b21fd2, I get an error when trying to run the xcodeproj target:

```
ERROR: Internal precondition failure:
At codingPath [targets, Index 55, linkerInputs, staticLibraries]: Decoded elements aren't unique (first duplicate at offset 73)
Please file a bug report at https://github.com/buildbuddy-io/rules_xcodeproj/issues/new?template=bug.md
```

This seems to be a recent regression. I do not get this error with 435cd30e1d4da0977eb9c7d63c98f4976dd856ae.

### PR DESCRIPTION
**Pull request by brentleyjones**
Fixes #764.

It seems that the same library can be in collected multiple times.

### CODE REVIEW

**Comment by jfirebaugh** [comment]
It does not fix it. I get the same error as before.

**Comment by brentleyjones** [comment]
Are you able to provide a repro? I can't reason why this would happen.

**Comment by jfirebaugh** [comment]
Here's a reduced test case: https://github.com/jfirebaugh/rules_xcode_reduction/tree/764

**Comment by brentleyjones** [comment]
Thank you for that! This PR should now fix it.

**Comment by brentleyjones** [comment]
You're welcome! ❤️

**Pull request merged**
