### PR TITLE
Support custom command line args and environment variables for test action

### PR DESCRIPTION
**Pull request by cgrindel**
Related to #906.

### CODE REVIEW

**Comment by cgrindel** [comment]
@brentleyjones It appears this test failure is a segmentation fault. I am unable to reproduce locally. Could you try rerunning this test in CI?

**Review by brentleyjones — APPROVED** [review]

**Comment by brentleyjones** [comment]
Still crashes from a clean workspace.

**Comment by cgrindel** [comment]
OK. I will investigate.

**Comment by cgrindel** [comment]
For future me, the segmentation fault appears to have been related to something in the remote cache causing the test runner to seg fault. We bumped the `cache_bust` value to force a rebuild and update the cache.

**Pull request merged**
